# Generated by Django 4.2.5 on 2023-10-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
    ]
