# Generated by Django 4.2.5 on 2023-10-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='id',
            new_name='class_id',
        ),
    ]
