# Generated by Django 4.2.5 on 2023-11-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='class_id',
            new_name='id',
        ),
    ]
