# Generated by Django 4.2.5 on 2023-10-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_rename_id_grade_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
