# Generated by Django 4.2.5 on 2023-10-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='Time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='no_of_student',
        ),
    ]
