# Generated by Django 4.2.5 on 2023-10-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_remove_batch_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
