# Generated by Django 4.2.5 on 2023-10-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_batch_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='grade',
            field=models.CharField(max_length=2),
        ),
    ]
