# Generated by Django 4.2.5 on 2023-10-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_alter_batch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
