# Generated by Django 4.2.5 on 2023-10-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_alter_batch_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='grade',
        ),
    ]
