# Generated by Django 4.2.5 on 2023-10-31 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('batch', '0010_batch_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='grades.grade'),
        ),
    ]
