# Generated by Django 4.2.4 on 2023-09-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0002_studententry_contact_no_studententry_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studententry',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='date_of_birth',
            field=models.DateField(default='1988-01-01'),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='fathers_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='grade',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='gurdians_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='mothers_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='peresent_adress',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='permanent_adress',
            field=models.TextField(max_length=100),
        ),
    ]
