# Generated by Django 4.2.4 on 2023-09-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0003_alter_studententry_contact_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studententry',
            old_name='gurdians_name',
            new_name='guardians_name',
        ),
        migrations.RenameField(
            model_name='studententry',
            old_name='peresent_adress',
            new_name='present_address',
        ),
    ]
