# Generated by Django 4.2.4 on 2023-09-11 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0005_alter_studententry_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studententry',
            old_name='permanent_adress',
            new_name='permanent_address',
        ),
    ]
