# Generated by Django 4.2.4 on 2023-09-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0006_rename_permanent_adress_studententry_permanent_address'),
    ]

    operations = [
    ]
