# Generated by Django 4.2.5 on 2023-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0007_auto_20230911_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studententry',
            name='contact_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='grade',
            field=models.PositiveIntegerField(max_length=12),
        ),
    ]
