# Generated by Django 4.2.5 on 2023-09-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0008_alter_studententry_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studententry',
            name='grade',
            field=models.CharField(max_length=12),
        ),
    ]
