# Generated by Django 4.2.5 on 2023-09-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0009_alter_studententry_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studententry',
            name='date_of_birth',
            field=models.CharField(default='1988-01-01', max_length=10000000),
        ),
    ]
