# Generated by Django 4.2.5 on 2023-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0011_rename_id_studententry_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studententry',
            name='contact_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
